**My First R Program**

1. Print

In [ ]:
print("Hello World")

[1] "Hello World"

2. Variables and data types

In [ ]:
myString <- ("Hello World")
num <- 10
floatingNum <- 9.5
isBool <- TRUE

class(myString)
class(num)
class(floatingNum)
class(isBool)

[1] "character"

[1] "numeric"

[1] "numeric"

[1] "logical"

3. Numerical Operator

In [ ]:
x <- 15
y <- 3

add <- x + y
diff <- x - y
prod <- x * y
qou <- x / y

print(sum)
print(diff)
print(prod)
print(qou)

cat("+", add)
cat()

[1] 18
[1] 12
[1] 45
[1] 5
+ 18

4. User Input

In [ ]:
name <- readline("Enter name: ")
print(paste("Name: ", name))
cat()

Enter name: Therese
[1] "Name:  Therese"

5. Decision making

In [ ]:
grade <- 89

if(grade <75){
  print ("Failed")
}else{
  print ("Passed")
}

[1] "Passed"

6. Loop

In [ ]:
for( i in 1:5){
  print (i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5

7. Functions

In [ ]:
addNumber <- function(a,b){
  return (a+b)
}
addNumber(5,8)

[1] 13

8. Vectors

In [ ]:
grades <- c(90, 88, 96, 83, 91)

cat("MEAN: ", mean(grades))
cat("\nMAX: ", max(grades))
cat("\nMIN: ", min(grades))
cat("\nSUM: ", sum(grades))
cat("\nLENGTH: ", length(grades))

MEAN:  89.6
MAX:  96
MIN:  83
SUM:  448
LENGTH:  5

9. Matrices

In [ ]:
A <- matrix(c(1, 2, 3, 4, 5, 6), nrow = 2)
A

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

10. Lists

In [ ]:
student <- list(
  Name = "John",
  Age = 20,
  GPA = 1.5
)

student

$Name
[1] "John"

$Age
[1] 20

$GPA
[1] 1.5

11. Data Frames

In [ ]:
students <- data.frame(
  Name =c("John", "Mary", "Anna"),
  Age = c(20, 19, 21),
  GPA = c(1.5, 1.8, 1.4)
)

students

write.csv(students, "student.csv")

  Name Age GPA
1 John 20  1.5
2 Mary 19  1.8
3 Anna 21  1.4

12. Reading CSV file

In [ ]:
data <- read.csv("student.csv")
head(data)

summary(data)

  X Name Age GPA
1 1 John 20  1.5
2 2 Mary 19  1.8
3 3 Anna 21  1.4

       X              Name        Age            GPA
 Min.   :1.0   Length   :3   Min.   :19.0   Min.   :1.400
 1st Qu.:1.5   N.unique :3   1st Qu.:19.5   1st Qu.:1.450
 Median :2.0   N.blank  :0   Median :20.0   Median :1.500
 Mean   :2.0   Min.nchar:4   Mean   :20.0   Mean   :1.567
 3rd Qu.:2.5   Max.nchar:4   3rd Qu.:20.5   3rd Qu.:1.650
 Max.   :3.0                 Max.   :21.0   Max.   :1.800